### ISSUE TITLE
opencv2/cudaimgproc.hpp: No such file or directory

### ISSUE THREAD

**Issue by HXB-1997** [cyrusbehr/YOLOv8-TensorRT-CPP#26]
`(CUDA113+CUDNN82) han@han:~/Desktop/hxb_projects/CPP_Instance/10-31/git-2/YOLOv8-TensorRT-CPP/build$ make
[  8%] Building CXX object libs/tensorrt-cpp-api/CMakeFiles/tensorrt_cpp_api.dir/src/engine.cpp.o
/home/han/Desktop/hxb_projects/CPP_Instance/10-31/git-2/YOLOv8-TensorRT-CPP/libs/tensorrt-cpp-api/src/engine.cpp:7:10: fatal error: opencv2/cudaimgproc.hpp: No such file or directory
    7 | #include <opencv2/cudaimgproc.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [libs/tensorrt-cpp-api/CMakeFiles/tensorrt_cpp_api.dir/build.make:76: libs/tensorrt-cpp-api/CMakeFiles/tensorrt_cpp_api.dir/src/engine.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:215: libs/tensorrt-cpp-api/CMakeFiles/tensorrt_cpp_api.dir/all] Error 2
make: *** [Makefile:91: all] Error 2`

**Comment by YumainOB** [comment]
Hello,

Looks like you are missing opencv_contib  includes. How did you get opencv(build from sources or distributed packages)?
 If you want more help please provide some system informations and take a look at https://github.com/cyrusbehr/tensorrt-cpp-api/blob/main/scripts/build_opencv.sh it may help you solving what i think your issue may be.

Best regards

**Comment by cyrusbehr** [comment]
@YumainOB is correct. Please be sure to compile OpenCV with CUDA support. Follow the instructions in the readme file: 
![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/17056751/c55e8013-1682-4d8c-8d4d-a17cf1d65390)


If you confirm that you have compiled OpenCV with CUDA support and still have issues, please reopen this issue.

**Comment by HXB-1997** [comment]
@cyrusbehr @YumainOB thank you so much. I'll have a try.

**Comment by huynhkhoa44** [comment]
@HXB-1997 @cyrusbehr  anyone have fixed this issue? I have tried both install opencv by another package and the script build_opencv.sh but I still have this issue.

**Comment by cyrusbehr** [comment]
@huynhkhoa44 can you provide more info on the issue you are facing. What is the error?

**Comment by huynhkhoa44** [comment]
I want to use script build_opencv.sh. I follow the instruction and modify my path to CUDNN LIBRARY and CUDNN INCLUDE DIR. 
![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/104811779/ee281a35-f2a5-4f5e-b7a0-3d37cda6a8e4)

And I run this file 
![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/104811779/2fa4c3ef-124d-4d4e-ad69-e1c3d58b5adc)

And this is my error
![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/104811779/757bb852-d8ed-4cee-a0d5-dbe3e2f7a02d)

**Comment by huynhkhoa44** [comment]
After error when use this code, I try to install opencv with CUDA by this link: https://www.youtube.com/watch?v=X6cXBqIz464. After install succesful, I build the project. But it has error like this issue when I run "make -j 8"
![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/104811779/909b9c40-2426-4290-8759-e0de9392ec30)

**Comment by cyrusbehr** [comment]
@huynhkhoa44 

Look at the screenshot you uploaded. Your OpenCV build script is failing: 

![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/17056751/5c600ebd-3fe9-45f8-b1aa-fb5b2676cb3d)

You can't proceed with building the project until you first build OpenCV properly. 

You probably need to modify these two arguments so that they point to the installation location of CUDNN on your system (I'm betting if you checked, those directories specified don't exist). 

![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/17056751/3a426374-a71e-4051-a98b-24168a2e6107)

Find our where your CUDNN is installed to. Once you'd done that, update the `CUDNN_INCLUDE_DIR` and `CUDNN_LIBRARY` arguments and rebuild OpenCV. If the build script still fails, then we can try to work to solve the issue.
